version: '3.3'

services:
  oracle:
    container_name: oracle
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PASSWORD=password
    volumes:
      - ./data:/opt/oracle/oradata

  backend:
    container_name: backend_spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/free
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./logs:/app/logs