server:
  port: 8002
  servlet:
    context-path: /modulo-02
  ssl:
    key-store: classpath:codefact.p12
    key-store-password: 123456
    enabled-protocols:
      - TLSv1.2
    protocol: TLS
    keyStoreType: PKCS12

spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        default_schema: ${ORACLE_USR}
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${ORACLE_URL}
    username: ${ORACLE_USR}
    password: ${ORACLE_PWD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
airline-api:
  openapi:
    dev-url: https://codefact.udea.edu.co/modulo-02/
    prod-url: https://codefact.udea.edu.co/modulo-02/

logging:
  level:
    root: debug
    org.springframework: debug
