server:
  port: 8080
  servlet:
    context-path: /sitas

spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        default_schema: ${ORACLE_USR}
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: ${ORACLE_USR}
    password: ${ORACLE_PWD}
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
    driver-class-name: oracle.jdbc.driver.OracleDriver
airline-api:
  openapi:
    dev-url: http://localhost:8080/sitas
    prod-url: https://sitas.com

logging:
  level:
    root: debug
    org.springframework: debug